### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Alexdrr** [francoism90/test-nginx-vod-module#1]
hi, are there any script examples for link generation?
can link examples?
many thanks

**Comment by francoism90** [comment]
I'm using PHP to generate the secure link: https://github.com/francoism90/mediadb/blob/master/app/Traits/Securable.php

Or do you mean something else, like the manifest URL?

Anyway, please see the media repository for details, I only used this one for testing and it's missing a few stuff.

**Comment by Alexdrr** [comment]
hello, i use this config

```
server {
 listen 80 ;
 server_name  local.com;

  vod_segment_duration 10000; # 2s
  vod_align_segments_to_key_frames on;
  vod_manifest_segment_durations_mode accurate;
  vod_last_modified 'Sun, 19 Nov 2000 08:52:00 GMT';
  vod_last_modified_types *;
  vod_mode local;
  #vod caches
  #vod_metadata_cache metadata_cache 512m;
  vod_response_cache response_cache 128m;

  vod_hls_absolute_index_urls off;


 location ~ ^/hls/([^/]+)/(.*) {
   vod_secret_key "password$1";
   root /home/user/vod/;
   vod hls;
   secure_token_encrypt_uri on;
   secure_token_encrypt_uri_key 7a653766427466265a7933335e59646731245450426b264b30456c6735464b79;
   secure_token_encrypt_uri_iv  6c7a314532512333557235716f313051;
   secure_token_encrypt_uri_part $1;
   secure_token_types application/vnd.apple.mpegurl;
 }

}
```


and use script for encryption link

`https://github.com/kaltura/nginx-secure-token-module/blob/master/scripts/encryptUrl.php`


get link

`php encryptUrl.php http://local.com/hls/ file.mp4 7a653766427466265a7933335e59646731245450426b264b30456c6735464b79 6c7a314532512333557235716f313051 `



get link

`http://local.com/hls/LwB2rnD7KByuEnHso9_AA29dPTLtWE6WOmZTYV57opg/index.m3u8 `

time of life this link is permanent, can i use your script which you give above for making encryption link and adding arguments for making link is temporary (expired by time)


thank you very much. I read all manuals on github, but cant find answer. Documentation of kaltura is very small.

**Comment by francoism90** [comment]
You can check out the project source for hopefully the answers you need. :)

The following two classes are used to generate JSON's that are used for the mapped configuration:
https://github.com/francoism90/mediadb/blob/master/app/Traits/Securable.php
https://github.com/francoism90/mediadb/blob/master/app/Traits/Streamable.php

I'm using DASH instead of HLS:
https://github.com/francoism90/mediadb/blob/master/doc/nginx/sites/vod-mapped.conf
https://github.com/francoism90/mediadb/blob/master/doc/nginx/sites/vod-local.conf

The links expires thanks to the `secure link` nginx module:
`secure_token "md5=$arg_md5&expires=$arg_expires&id=$arg_id";`

**Comment by Alexdrr** [comment]
Thank you for your answer, did you have experience creating a proxy server for secure links?
on the github of the module it is written that it does not support the proxy_cache location in the vod location.

**Comment by francoism90** [comment]
I'm injecting the token into the manifest as this includes the expiring token. I don't think one should use proxy_cache when using expire tokens or at least should be the equal to the expire time.

The module already provides caching options, would there be a benefit using proxy_cache?

**Comment by Alexdrr** [comment]
tell me the input of current into the manifest passes through the kaltura module? I think you can configure a cache exception for manifest.

the benefit of saving on ssd disks, ssd only for cache, hdd for storage. I have good experience with this, but on a different stream server (not nginx)

**Comment by francoism90** [comment]
Do you mean the actual manifest file? And could you show what you mean with the cache exception?
What other streaming services do you use except the nginx one?

**Comment by Alexdrr** [comment]
I meant to exclude * .m3u8 from the cache, I used flussonic, it allows you to cache video on an ssd disk.
As a result, I made akamai token, and link encryption, the problem is solved, thank you for your help!
